version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  sample:
    jobs:
      - build_and_test:
          executor: node/default
          steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run:
                command: yarn start
                name: Run App
